// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package repo

import (
	"context"
)

const createPasswordResetRecord = `-- name: CreatePasswordResetRecord :one
insert into password_reset
  (user_email)
values
  (?1)
returning code, user_email, created_at
`

func (q *Queries) CreatePasswordResetRecord(ctx context.Context, email string) (PasswordReset, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetRecord, email)
	var i PasswordReset
	err := row.Scan(&i.Code, &i.UserEmail, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into profile
  (email, username, displayname, color, password)
values
  (?1, ?2, ?3, ?4, ?5)
returning id, email, username, displayname, color, image_url, email_verified, password, access_token, refresh_token, created_at, updated_at
`

type CreateUserParams struct {
	Email       string `json:"email"`
	Username    string `json:"username"`
	Displayname string `json:"displayname"`
	Color       string `json:"color"`
	Password    string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.Displayname,
		arg.Color,
		arg.Password,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Displayname,
		&i.Color,
		&i.ImageUrl,
		&i.EmailVerified,
		&i.Password,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVerificationRecord = `-- name: CreateVerificationRecord :exec
insert into email_verification
  (user_id, code)
values
  (?1, ?2)
`

type CreateVerificationRecordParams struct {
	UserID string `json:"userId"`
	Code   string `json:"code"`
}

func (q *Queries) CreateVerificationRecord(ctx context.Context, arg CreateVerificationRecordParams) error {
	_, err := q.db.ExecContext(ctx, createVerificationRecord, arg.UserID, arg.Code)
	return err
}

const deletePasswordResetRecord = `-- name: DeletePasswordResetRecord :exec
delete from password_reset where user_email = ?1
`

func (q *Queries) DeletePasswordResetRecord(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetRecord, email)
	return err
}

const deleteUnverifiedAccount = `-- name: DeleteUnverifiedAccount :exec
delete from profile where email_verified = false
and (email = ?1 or username = ?2)
`

type DeleteUnverifiedAccountParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

func (q *Queries) DeleteUnverifiedAccount(ctx context.Context, arg DeleteUnverifiedAccountParams) error {
	_, err := q.db.ExecContext(ctx, deleteUnverifiedAccount, arg.Email, arg.Username)
	return err
}

const deleteVerificationRecord = `-- name: DeleteVerificationRecord :exec
delete from email_verification where user_id = ?1
`

func (q *Queries) DeleteVerificationRecord(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteVerificationRecord, userID)
	return err
}

const getPasswordResetByCode = `-- name: GetPasswordResetByCode :one
select
  pr.code,
  p.id
from password_reset pr
join profile p on pr.user_email = p.email
where code = ?1
`

type GetPasswordResetByCodeRow struct {
	Code string `json:"code"`
	ID   string `json:"id"`
}

func (q *Queries) GetPasswordResetByCode(ctx context.Context, code string) (GetPasswordResetByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetByCode, code)
	var i GetPasswordResetByCodeRow
	err := row.Scan(&i.Code, &i.ID)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, username, displayname, color, image_url, email_verified, password, access_token, refresh_token, created_at, updated_at from profile where email = ?1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Displayname,
		&i.Color,
		&i.ImageUrl,
		&i.EmailVerified,
		&i.Password,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, username, displayname, color, image_url, email_verified, password, access_token, refresh_token, created_at, updated_at from profile where id = ?1
`

func (q *Queries) GetUserByID(ctx context.Context, userID string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Displayname,
		&i.Color,
		&i.ImageUrl,
		&i.EmailVerified,
		&i.Password,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, email, username, displayname, color, image_url, email_verified, password, access_token, refresh_token, created_at, updated_at from profile where username = ?1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Displayname,
		&i.Color,
		&i.ImageUrl,
		&i.EmailVerified,
		&i.Password,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerificationByCode = `-- name: GetVerificationByCode :one
select code, user_id, created_at from email_verification where code = ?1
`

func (q *Queries) GetVerificationByCode(ctx context.Context, code string) (EmailVerification, error) {
	row := q.db.QueryRowContext(ctx, getVerificationByCode, code)
	var i EmailVerification
	err := row.Scan(&i.Code, &i.UserID, &i.CreatedAt)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
update profile set password = ?1 where id = ?2
`

type UpdatePasswordParams struct {
	HashedPassword string `json:"hashedPassword"`
	UserID         string `json:"userId"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.HashedPassword, arg.UserID)
	return err
}

const verifyUser = `-- name: VerifyUser :one
update profile
set email_verified = true
where id = ?1
returning id, email, username, displayname, color, image_url, email_verified, password, access_token, refresh_token, created_at, updated_at
`

func (q *Queries) VerifyUser(ctx context.Context, userID string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, verifyUser, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Displayname,
		&i.Color,
		&i.ImageUrl,
		&i.EmailVerified,
		&i.Password,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
