// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: definition.sql

package repo

import (
	"context"
)

const createDefinition = `-- name: CreateDefinition :exec
insert into definition
  (word, content)
values
  (?1, ?2)
`

type CreateDefinitionParams struct {
	Word    string `json:"word"`
	Content string `json:"content"`
}

func (q *Queries) CreateDefinition(ctx context.Context, arg CreateDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, createDefinition, arg.Word, arg.Content)
	return err
}

const getDefinitions = `-- name: GetDefinitions :many
select word, content, created_at, updated_at from definition where word = ?1
`

func (q *Queries) GetDefinitions(ctx context.Context, word string) ([]Definition, error) {
	rows, err := q.db.QueryContext(ctx, getDefinitions, word)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Definition
	for rows.Next() {
		var i Definition
		if err := rows.Scan(
			&i.Word,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
