// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"time"
)

type Definition struct {
	Word      string    `json:"word"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type EmailVerification struct {
	Code      string    `json:"code"`
	UserID    string    `json:"userId"`
	CreatedAt time.Time `json:"createdAt"`
}

type PasswordReset struct {
	Code      string    `json:"code"`
	UserEmail string    `json:"userEmail"`
	CreatedAt time.Time `json:"createdAt"`
}

type Post struct {
	ID            string    `json:"id"`
	UserID        string    `json:"userId"`
	Visibility    string    `json:"visibility"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	Word          string    `json:"word"`
	Definition    string    `json:"definition"`
	PartOfSpeech  string    `json:"partOfSpeech"`
	Pronunciation string    `json:"pronunciation"`
	Example       string    `json:"example"`
	Synonyms      string    `json:"synonyms"`
	Antonyms      string    `json:"antonyms"`
}

type PostBookmark struct {
	UserID    string    `json:"userId"`
	PostID    string    `json:"postId"`
	CreatedAt time.Time `json:"createdAt"`
}

type PostLike struct {
	UserID    string    `json:"userId"`
	PostID    string    `json:"postId"`
	CreatedAt time.Time `json:"createdAt"`
}

type Profile struct {
	ID            string    `json:"id"`
	Email         string    `json:"email"`
	Username      string    `json:"username"`
	Displayname   string    `json:"displayname"`
	Color         string    `json:"color"`
	ImageUrl      *string   `json:"imageUrl"`
	EmailVerified bool      `json:"emailVerified"`
	Password      string    `json:"password"`
	AccessToken   *string   `json:"accessToken"`
	RefreshToken  *string   `json:"refreshToken"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type UserFollow struct {
	FollowerID string    `json:"followerId"`
	FolloweeID string    `json:"followeeId"`
	CreatedAt  time.Time `json:"createdAt"`
}
