// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package repo

import (
	"context"
	"time"
)

const bookmarkPost = `-- name: BookmarkPost :exec
insert into post_bookmark
  (post_id, user_id)
values
  (?1, ?2)
`

type BookmarkPostParams struct {
	PostID string `json:"postId"`
	UserID string `json:"userId"`
}

func (q *Queries) BookmarkPost(ctx context.Context, arg BookmarkPostParams) error {
	_, err := q.db.ExecContext(ctx, bookmarkPost, arg.PostID, arg.UserID)
	return err
}

const createPost = `-- name: CreatePost :one
insert into post
  (word, definition, part_of_speech, pronunciation,
  synonyms, antonyms, example, visibility, user_id)
values
  (?1, ?2, ?3,
  ?4, ?5, ?6,
  ?7, ?8, ?9)
returning id, user_id, visibility, created_at, updated_at, word, definition, part_of_speech, pronunciation, example, synonyms, antonyms
`

type CreatePostParams struct {
	Word          string `json:"word"`
	Definition    string `json:"definition"`
	PartOfSpeech  string `json:"partOfSpeech"`
	Pronunciation string `json:"pronunciation"`
	Synonyms      string `json:"synonyms"`
	Antonyms      string `json:"antonyms"`
	Example       string `json:"example"`
	Visibility    string `json:"visibility"`
	UserID        string `json:"userId"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.Word,
		arg.Definition,
		arg.PartOfSpeech,
		arg.Pronunciation,
		arg.Synonyms,
		arg.Antonyms,
		arg.Example,
		arg.Visibility,
		arg.UserID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Word,
		&i.Definition,
		&i.PartOfSpeech,
		&i.Pronunciation,
		&i.Example,
		&i.Synonyms,
		&i.Antonyms,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
delete from post where id = ?1
`

func (q *Queries) DeletePost(ctx context.Context, postID string) error {
	_, err := q.db.ExecContext(ctx, deletePost, postID)
	return err
}

const getFollowingPosts = `-- name: GetFollowingPosts :many
SELECT
  p.id, p.visibility, p.created_at, p.updated_at, p.user_id,
  p.word, p.definition, p.part_of_speech, p.pronunciation,
  p.synonyms, p.antonyms, p.example,
  u.username, u.displayname, u.image_url, u.color,
  COALESCE(lc.count, 0) AS like_count,
  COALESCE(bc.count, 0) AS bookmark_count,
  EXISTS (
    SELECT 1 FROM post_like pl
    WHERE pl.post_id = p.id AND pl.user_id = ?1
  ) AS is_liked,
  EXISTS (
    SELECT 1 FROM post_bookmark pb
    WHERE pb.post_id = p.id AND pb.user_id = ?1
  ) AS is_bookmarked
FROM post p
JOIN profile u ON p.user_id = u.id
LEFT JOIN (
    SELECT post_id, COUNT(*) as count 
    FROM post_like GROUP BY post_id
) lc ON lc.post_id = p.id
LEFT JOIN (
    SELECT post_id, COUNT(*) as count 
    FROM post_bookmark GROUP BY post_id
) bc ON bc.post_id = p.id
WHERE
  p.visibility = 'public'
  AND p.user_id IN (
    SELECT followee_id FROM user_follows 
    WHERE follower_id = ?1
  )
ORDER BY p.created_at DESC
LIMIT ?3 OFFSET ?2
`

type GetFollowingPostsParams struct {
	UserID string `json:"userId"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

type GetFollowingPostsRow struct {
	ID            string    `json:"id"`
	Visibility    string    `json:"visibility"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	UserID        string    `json:"userId"`
	Word          string    `json:"word"`
	Definition    string    `json:"definition"`
	PartOfSpeech  string    `json:"partOfSpeech"`
	Pronunciation string    `json:"pronunciation"`
	Synonyms      string    `json:"synonyms"`
	Antonyms      string    `json:"antonyms"`
	Example       string    `json:"example"`
	Username      string    `json:"username"`
	Displayname   string    `json:"displayname"`
	ImageUrl      *string   `json:"imageUrl"`
	Color         string    `json:"color"`
	LikeCount     int64     `json:"likeCount"`
	BookmarkCount int64     `json:"bookmarkCount"`
	IsLiked       int64     `json:"isLiked"`
	IsBookmarked  int64     `json:"isBookmarked"`
}

func (q *Queries) GetFollowingPosts(ctx context.Context, arg GetFollowingPostsParams) ([]GetFollowingPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowingPosts, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowingPostsRow
	for rows.Next() {
		var i GetFollowingPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Word,
			&i.Definition,
			&i.PartOfSpeech,
			&i.Pronunciation,
			&i.Synonyms,
			&i.Antonyms,
			&i.Example,
			&i.Username,
			&i.Displayname,
			&i.ImageUrl,
			&i.Color,
			&i.LikeCount,
			&i.BookmarkCount,
			&i.IsLiked,
			&i.IsBookmarked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfilePosts = `-- name: GetProfilePosts :many
SELECT
  p.id, p.visibility, p.created_at, p.updated_at, p.user_id,
  p.word, p.definition, p.part_of_speech, p.pronunciation,
  p.synonyms, p.antonyms, p.example,
  u.username, u.displayname, u.image_url, u.color,
  COALESCE(lc.count, 0) AS like_count,
  COALESCE(bc.count, 0) AS bookmark_count,
  EXISTS (
    SELECT 1 FROM post_like pl
    WHERE pl.post_id = p.id AND pl.user_id = ?1
  ) AS is_liked,
  EXISTS (
    SELECT 1 FROM post_bookmark pb
    WHERE pb.post_id = p.id AND pb.user_id = ?1
  ) AS is_bookmarked
FROM post p
JOIN profile u ON p.user_id = u.id
LEFT JOIN (
    SELECT post_id, COUNT(*) as count 
    FROM post_like GROUP BY post_id
) lc ON lc.post_id = p.id
LEFT JOIN (
    SELECT post_id, COUNT(*) as count 
    FROM post_bookmark GROUP BY post_id
) bc ON bc.post_id = p.id
WHERE
  (?2 OR p.visibility = 'public')
  AND p.user_id = ?3
ORDER BY p.created_at DESC
LIMIT ?5 OFFSET ?4
`

type GetProfilePostsParams struct {
	UserID        string      `json:"userId"`
	CanSeePrivate interface{} `json:"canSeePrivate"`
	ProfileID     string      `json:"profileId"`
	Offset        int64       `json:"offset"`
	Limit         int64       `json:"limit"`
}

type GetProfilePostsRow struct {
	ID            string    `json:"id"`
	Visibility    string    `json:"visibility"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	UserID        string    `json:"userId"`
	Word          string    `json:"word"`
	Definition    string    `json:"definition"`
	PartOfSpeech  string    `json:"partOfSpeech"`
	Pronunciation string    `json:"pronunciation"`
	Synonyms      string    `json:"synonyms"`
	Antonyms      string    `json:"antonyms"`
	Example       string    `json:"example"`
	Username      string    `json:"username"`
	Displayname   string    `json:"displayname"`
	ImageUrl      *string   `json:"imageUrl"`
	Color         string    `json:"color"`
	LikeCount     int64     `json:"likeCount"`
	BookmarkCount int64     `json:"bookmarkCount"`
	IsLiked       int64     `json:"isLiked"`
	IsBookmarked  int64     `json:"isBookmarked"`
}

func (q *Queries) GetProfilePosts(ctx context.Context, arg GetProfilePostsParams) ([]GetProfilePostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProfilePosts,
		arg.UserID,
		arg.CanSeePrivate,
		arg.ProfileID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfilePostsRow
	for rows.Next() {
		var i GetProfilePostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Word,
			&i.Definition,
			&i.PartOfSpeech,
			&i.Pronunciation,
			&i.Synonyms,
			&i.Antonyms,
			&i.Example,
			&i.Username,
			&i.Displayname,
			&i.ImageUrl,
			&i.Color,
			&i.LikeCount,
			&i.BookmarkCount,
			&i.IsLiked,
			&i.IsBookmarked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentPosts = `-- name: GetRecentPosts :many
SELECT
  p.id, p.visibility, p.created_at, p.updated_at, p.user_id,
  p.word, p.definition, p.part_of_speech, p.pronunciation,
  p.synonyms, p.antonyms, p.example,
  u.username, u.displayname, u.image_url, u.color,
  COALESCE(lc.count, 0) AS like_count,
  COALESCE(bc.count, 0) AS bookmark_count,
  EXISTS (
    SELECT 1 FROM post_like pl
    WHERE pl.post_id = p.id AND pl.user_id = ?1
  ) AS is_liked,
  EXISTS (
    SELECT 1 FROM post_bookmark pb
    WHERE pb.post_id = p.id AND pb.user_id = ?1
  ) AS is_bookmarked
FROM post p
JOIN profile u ON p.user_id = u.id
LEFT JOIN (
    SELECT post_id, COUNT(*) as count 
    FROM post_like GROUP BY post_id
) lc ON lc.post_id = p.id
LEFT JOIN (
    SELECT post_id, COUNT(*) as count 
    FROM post_bookmark GROUP BY post_id
) bc ON bc.post_id = p.id
WHERE
  p.visibility = 'public'
  OR p.user_id = ?1
ORDER BY p.created_at DESC
LIMIT ?3 OFFSET ?2
`

type GetRecentPostsParams struct {
	UserID string `json:"userId"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

type GetRecentPostsRow struct {
	ID            string    `json:"id"`
	Visibility    string    `json:"visibility"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	UserID        string    `json:"userId"`
	Word          string    `json:"word"`
	Definition    string    `json:"definition"`
	PartOfSpeech  string    `json:"partOfSpeech"`
	Pronunciation string    `json:"pronunciation"`
	Synonyms      string    `json:"synonyms"`
	Antonyms      string    `json:"antonyms"`
	Example       string    `json:"example"`
	Username      string    `json:"username"`
	Displayname   string    `json:"displayname"`
	ImageUrl      *string   `json:"imageUrl"`
	Color         string    `json:"color"`
	LikeCount     int64     `json:"likeCount"`
	BookmarkCount int64     `json:"bookmarkCount"`
	IsLiked       int64     `json:"isLiked"`
	IsBookmarked  int64     `json:"isBookmarked"`
}

func (q *Queries) GetRecentPosts(ctx context.Context, arg GetRecentPostsParams) ([]GetRecentPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentPosts, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentPostsRow
	for rows.Next() {
		var i GetRecentPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Word,
			&i.Definition,
			&i.PartOfSpeech,
			&i.Pronunciation,
			&i.Synonyms,
			&i.Antonyms,
			&i.Example,
			&i.Username,
			&i.Displayname,
			&i.ImageUrl,
			&i.Color,
			&i.LikeCount,
			&i.BookmarkCount,
			&i.IsLiked,
			&i.IsBookmarked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalFollowingPostCount = `-- name: GetTotalFollowingPostCount :one
select
  count(*)
from post
where 
  user_id in (select followee_id from user_follows where follower_id = ?1)
`

func (q *Queries) GetTotalFollowingPostCount(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalFollowingPostCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalPostCount = `-- name: GetTotalPostCount :one
select count(*) from post
`

func (q *Queries) GetTotalPostCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalPostCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalProfilePostCount = `-- name: GetTotalProfilePostCount :one
select
  count(*)
from post
where
  user_id = ?1
  and (?2 or visibility = 'public')
`

type GetTotalProfilePostCountParams struct {
	ProfileID     string      `json:"profileId"`
	CanSeePrivate interface{} `json:"canSeePrivate"`
}

func (q *Queries) GetTotalProfilePostCount(ctx context.Context, arg GetTotalProfilePostCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalProfilePostCount, arg.ProfileID, arg.CanSeePrivate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const likePost = `-- name: LikePost :exec
insert into post_like
  (post_id, user_id)
values
  (?1, ?2)
`

type LikePostParams struct {
	PostID string `json:"postId"`
	UserID string `json:"userId"`
}

func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) error {
	_, err := q.db.ExecContext(ctx, likePost, arg.PostID, arg.UserID)
	return err
}

const unbookmarkPost = `-- name: UnbookmarkPost :exec
delete from post_bookmark
where
  post_id = ?1
  and user_id = ?2
`

type UnbookmarkPostParams struct {
	PostID string `json:"postId"`
	UserID string `json:"userId"`
}

func (q *Queries) UnbookmarkPost(ctx context.Context, arg UnbookmarkPostParams) error {
	_, err := q.db.ExecContext(ctx, unbookmarkPost, arg.PostID, arg.UserID)
	return err
}

const unlikePost = `-- name: UnlikePost :exec
delete from post_like
where
  post_id = ?1
  and user_id = ?2
`

type UnlikePostParams struct {
	PostID string `json:"postId"`
	UserID string `json:"userId"`
}

func (q *Queries) UnlikePost(ctx context.Context, arg UnlikePostParams) error {
	_, err := q.db.ExecContext(ctx, unlikePost, arg.PostID, arg.UserID)
	return err
}
