// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package repo

import (
	"context"
)

const followUser = `-- name: FollowUser :exec
insert into user_follows
  (follower_id, followee_id)
values
  (?1, ?2)
`

type FollowUserParams struct {
	FollowerID string `json:"followerId"`
	FolloweeID string `json:"followeeId"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.ExecContext(ctx, followUser, arg.FollowerID, arg.FolloweeID)
	return err
}

const getFollowers = `-- name: GetFollowers :many
select
  id,
  email,
  username,
  displayname,
  image_url,
  color
from profile
where id in (select follower_id from user_follows where followee_id = ?1)
limit ?3
offset ?2
`

type GetFollowersParams struct {
	UserID string `json:"userId"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

type GetFollowersRow struct {
	ID          string  `json:"id"`
	Email       string  `json:"email"`
	Username    string  `json:"username"`
	Displayname string  `json:"displayname"`
	ImageUrl    *string `json:"imageUrl"`
	Color       string  `json:"color"`
}

func (q *Queries) GetFollowers(ctx context.Context, arg GetFollowersParams) ([]GetFollowersRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowers, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowersRow
	for rows.Next() {
		var i GetFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Displayname,
			&i.ImageUrl,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowersCount = `-- name: GetFollowersCount :one
select count(*) from user_follows where followee_id = ?1
`

func (q *Queries) GetFollowersCount(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFollowersCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFollowing = `-- name: GetFollowing :many
select
  id,
  email,
  username,
  displayname,
  image_url,
  color
from profile
where id in (select followee_id from user_follows where follower_id = ?1)
limit ?3
offset ?2
`

type GetFollowingParams struct {
	UserID string `json:"userId"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

type GetFollowingRow struct {
	ID          string  `json:"id"`
	Email       string  `json:"email"`
	Username    string  `json:"username"`
	Displayname string  `json:"displayname"`
	ImageUrl    *string `json:"imageUrl"`
	Color       string  `json:"color"`
}

func (q *Queries) GetFollowing(ctx context.Context, arg GetFollowingParams) ([]GetFollowingRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowing, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowingRow
	for rows.Next() {
		var i GetFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Displayname,
			&i.ImageUrl,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingCount = `-- name: GetFollowingCount :one
select count(*) from user_follows where follower_id = ?1
`

func (q *Queries) GetFollowingCount(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFollowingCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProfile = `-- name: GetProfile :one
select
  u.id,
  u.email,
  u.username,
  u.displayname,
  u.image_url,
  u.color,
  (select count(*) from post where user_id = u.id) as post_count,
  (select count(*) from user_follows f1 where f1.followee_id = u.id) as following_count,
  (select count(*) from user_follows f2 where f2.follower_id = u.id) as follower_count,
  coalesce((select 1 from user_follows f3 where f3.follower_id = ?1 and f3.followee_id = u.id), 0) as is_following
from profile u
where u.id = ?2
`

type GetProfileParams struct {
	UserID    string `json:"userId"`
	ProfileID string `json:"profileId"`
}

type GetProfileRow struct {
	ID             string      `json:"id"`
	Email          string      `json:"email"`
	Username       string      `json:"username"`
	Displayname    string      `json:"displayname"`
	ImageUrl       *string     `json:"imageUrl"`
	Color          string      `json:"color"`
	PostCount      int64       `json:"postCount"`
	FollowingCount int64       `json:"followingCount"`
	FollowerCount  int64       `json:"followerCount"`
	IsFollowing    interface{} `json:"isFollowing"`
}

func (q *Queries) GetProfile(ctx context.Context, arg GetProfileParams) (GetProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getProfile, arg.UserID, arg.ProfileID)
	var i GetProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Displayname,
		&i.ImageUrl,
		&i.Color,
		&i.PostCount,
		&i.FollowingCount,
		&i.FollowerCount,
		&i.IsFollowing,
	)
	return i, err
}

const unfollowUser = `-- name: UnfollowUser :exec
delete from user_follows
where
  follower_id = ?1
  and followee_id = ?2
`

type UnfollowUserParams struct {
	FollowerID string `json:"followerId"`
	FolloweeID string `json:"followeeId"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.ExecContext(ctx, unfollowUser, arg.FollowerID, arg.FolloweeID)
	return err
}
