/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAuthenticatedRouteImport } from './routes/app/_authenticated'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppAuthenticatedIndexRouteImport } from './routes/app/_authenticated/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AppAuthenticatedPostRouteImport } from './routes/app/_authenticated/post'
import { Route as AppAuthenticatedDefineRouteImport } from './routes/app/_authenticated/define'
import { Route as AuthVerifyIdRouteImport } from './routes/_auth/verify/$id'
import { Route as AuthResetPasswordCodeRouteImport } from './routes/_auth/reset-password/$code'
import { Route as AppAuthenticatedProfileIndexRouteImport } from './routes/app/_authenticated/profile/index'
import { Route as AppAuthenticatedProfileEditRouteImport } from './routes/app/_authenticated/profile/edit'
import { Route as AppAuthenticatedProfileProfileIdRouteImport } from './routes/app/_authenticated/profile/$profileId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedRoute = AppAuthenticatedRouteImport.update({
  id: '/app/_authenticated',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppAuthenticatedIndexRoute = AppAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRoute,
} as any)
const AppAuthenticatedPostRoute = AppAuthenticatedPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)
const AppAuthenticatedDefineRoute = AppAuthenticatedDefineRouteImport.update({
  id: '/define',
  path: '/define',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)
const AuthVerifyIdRoute = AuthVerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordCodeRoute = AuthResetPasswordCodeRouteImport.update({
  id: '/reset-password/$code',
  path: '/reset-password/$code',
  getParentRoute: () => AuthRoute,
} as any)
const AppAuthenticatedProfileIndexRoute =
  AppAuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedProfileEditRoute =
  AppAuthenticatedProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedProfileProfileIdRoute =
  AppAuthenticatedProfileProfileIdRouteImport.update({
    id: '/profile/$profileId',
    path: '/profile/$profileId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/app': typeof AppAuthenticatedRouteWithChildren
  '/reset-password/$code': typeof AuthResetPasswordCodeRoute
  '/verify/$id': typeof AuthVerifyIdRoute
  '/app/define': typeof AppAuthenticatedDefineRoute
  '/app/post': typeof AppAuthenticatedPostRoute
  '/reset-password/': typeof AuthResetPasswordIndexRoute
  '/app/': typeof AppAuthenticatedIndexRoute
  '/app/profile/$profileId': typeof AppAuthenticatedProfileProfileIdRoute
  '/app/profile/edit': typeof AppAuthenticatedProfileEditRoute
  '/app/profile/': typeof AppAuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password/$code': typeof AuthResetPasswordCodeRoute
  '/verify/$id': typeof AuthVerifyIdRoute
  '/app/define': typeof AppAuthenticatedDefineRoute
  '/app/post': typeof AppAuthenticatedPostRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/app': typeof AppAuthenticatedIndexRoute
  '/app/profile/$profileId': typeof AppAuthenticatedProfileProfileIdRoute
  '/app/profile/edit': typeof AppAuthenticatedProfileEditRoute
  '/app/profile': typeof AppAuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/app/_authenticated': typeof AppAuthenticatedRouteWithChildren
  '/_auth/reset-password/$code': typeof AuthResetPasswordCodeRoute
  '/_auth/verify/$id': typeof AuthVerifyIdRoute
  '/app/_authenticated/define': typeof AppAuthenticatedDefineRoute
  '/app/_authenticated/post': typeof AppAuthenticatedPostRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/app/_authenticated/': typeof AppAuthenticatedIndexRoute
  '/app/_authenticated/profile/$profileId': typeof AppAuthenticatedProfileProfileIdRoute
  '/app/_authenticated/profile/edit': typeof AppAuthenticatedProfileEditRoute
  '/app/_authenticated/profile/': typeof AppAuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/app'
    | '/reset-password/$code'
    | '/verify/$id'
    | '/app/define'
    | '/app/post'
    | '/reset-password/'
    | '/app/'
    | '/app/profile/$profileId'
    | '/app/profile/edit'
    | '/app/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password/$code'
    | '/verify/$id'
    | '/app/define'
    | '/app/post'
    | '/reset-password'
    | '/app'
    | '/app/profile/$profileId'
    | '/app/profile/edit'
    | '/app/profile'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/login'
    | '/_auth/register'
    | '/app/_authenticated'
    | '/_auth/reset-password/$code'
    | '/_auth/verify/$id'
    | '/app/_authenticated/define'
    | '/app/_authenticated/post'
    | '/_auth/reset-password/'
    | '/app/_authenticated/'
    | '/app/_authenticated/profile/$profileId'
    | '/app/_authenticated/profile/edit'
    | '/app/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AppAuthenticatedRoute: typeof AppAuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated': {
      id: '/app/_authenticated'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/_authenticated/': {
      id: '/app/_authenticated/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthenticatedIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/_authenticated/post': {
      id: '/app/_authenticated/post'
      path: '/post'
      fullPath: '/app/post'
      preLoaderRoute: typeof AppAuthenticatedPostRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/define': {
      id: '/app/_authenticated/define'
      path: '/define'
      fullPath: '/app/define'
      preLoaderRoute: typeof AppAuthenticatedDefineRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/_auth/verify/$id': {
      id: '/_auth/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof AuthVerifyIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password/$code': {
      id: '/_auth/reset-password/$code'
      path: '/reset-password/$code'
      fullPath: '/reset-password/$code'
      preLoaderRoute: typeof AuthResetPasswordCodeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/_authenticated/profile/': {
      id: '/app/_authenticated/profile/'
      path: '/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppAuthenticatedProfileIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/profile/edit': {
      id: '/app/_authenticated/profile/edit'
      path: '/profile/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppAuthenticatedProfileEditRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/profile/$profileId': {
      id: '/app/_authenticated/profile/$profileId'
      path: '/profile/$profileId'
      fullPath: '/app/profile/$profileId'
      preLoaderRoute: typeof AppAuthenticatedProfileProfileIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordCodeRoute: typeof AuthResetPasswordCodeRoute
  AuthVerifyIdRoute: typeof AuthVerifyIdRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordCodeRoute: AuthResetPasswordCodeRoute,
  AuthVerifyIdRoute: AuthVerifyIdRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AppAuthenticatedRouteChildren {
  AppAuthenticatedDefineRoute: typeof AppAuthenticatedDefineRoute
  AppAuthenticatedPostRoute: typeof AppAuthenticatedPostRoute
  AppAuthenticatedIndexRoute: typeof AppAuthenticatedIndexRoute
  AppAuthenticatedProfileProfileIdRoute: typeof AppAuthenticatedProfileProfileIdRoute
  AppAuthenticatedProfileEditRoute: typeof AppAuthenticatedProfileEditRoute
  AppAuthenticatedProfileIndexRoute: typeof AppAuthenticatedProfileIndexRoute
}

const AppAuthenticatedRouteChildren: AppAuthenticatedRouteChildren = {
  AppAuthenticatedDefineRoute: AppAuthenticatedDefineRoute,
  AppAuthenticatedPostRoute: AppAuthenticatedPostRoute,
  AppAuthenticatedIndexRoute: AppAuthenticatedIndexRoute,
  AppAuthenticatedProfileProfileIdRoute: AppAuthenticatedProfileProfileIdRoute,
  AppAuthenticatedProfileEditRoute: AppAuthenticatedProfileEditRoute,
  AppAuthenticatedProfileIndexRoute: AppAuthenticatedProfileIndexRoute,
}

const AppAuthenticatedRouteWithChildren =
  AppAuthenticatedRoute._addFileChildren(AppAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AppAuthenticatedRoute: AppAuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
